env:
  browser: true
  node   : true
  es6    : true

parser : babel-eslint
extends: airbnb-base
plugins:
  - babel

rules:
  indent:
    - 2
    - 2
  no-var: 1
  vars-on-top: 0
  func-names: 2
  prefer-const: 0
  comma-dangle: 0
  padded-blocks: 0
  no-param-reassign: 0
  no-multi-spaces:
    - 2
    - exceptions:
        ImportDeclaration : true
        VariableDeclarator: true
        AssignmentExpression: true
